<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
function scib_theme_suggestions_block_alter(array &$suggestions, array $variables) {
	// Block suggestions for custom block bundles.
	if (isset($variables['elements']['content']['#block_content'])) {
		array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
	}
}